
export const Routes = {
    Auth: "Auth",

    Auth_Stack: "AuthStack",
    Login: "Login",
    SignUp: "SignUp",

    FirstPage: "FirstPage",
    PhoneNumScreen: "PhoneNumScreen",
    OTPScreen: "OTPScreen",
    EmailScreen: "EmailScreen",
    NameScreen: "NameScreen",
    ProfileScreen: "ProfileScreen",
    DOBScreen: "DOBScreen",
    TradingScreen: "TradingScreen",
    NationalityScreen: "NationalityScreen",
    BusinessNameScreen: "BusinessNameScreen",
    BusinessEmailScreen: "BusinessEmailScreen",
    BusinessAddress: "BusinessAddress",
    BusinessYourAddress: "BusinessYourAddress",
    BusinessOwner: "BusinessOwner",
    BusinessUBO1: 'BusinessUBO1',
    BusinessUBO2: 'BusinessUBO2',
    PersonDetails: "PersonDetails",
    BankDetailsScreen: "BankDetailsScreen",
    DocUploadScreen: "DocUploadScreen",
    ShareScreen: "ShareScreen",
    CongratsScreen: "CongratsScreen",


    SignUp_Otp: "SignUpOtp",
    Sidebar_Menu: "SidebarMenu",

    App_Navigator: "AppNavigator",
    App_Drawer: "AppDrawer",
    My_Profile: "MyProfile",
    Personal_Information: "PersonalInformation",
    Contact_Information: "ContactInformation",
    Financial_Information: "FinancialInformation",
    TradingAddress: "Trading_Address",
    RegisteredAddress: "Registred_Address",
    Job_Listing: "JobListing",
    Milestone_Listing: "MilestoneListing",
    Milestone_Listing_Client: "MilestoneListingClient",
    Milestone_Detail: "MilestoneDetail",
    Milestone_Updates: "MilestoneUpdates",
    Job_Details: "JobDetails",
    Create_New_Job: "CreateNewJob",
    Edit_Job: "EditJob",
    Create_Contract: "CreateContract",
    Update_Contract: "UpdateContract",
    Add_Milestone: "AddMilestone",
    Contract_Modification_Requests: "ContractModificationRequests",
    Milestone_Modification_Requests: "MilestoneModificationRequests",
    Send_Modification_Requests: "SendModificationRequests",
    Client_Milestone_Detail: "ClientMilestoneDetail",
    Chat_View: "ChatView",
    CardView: "CardView",
    Work_Progress_List: "WorkProgressList",
    Work_Progress_Detail: "WorkProgressDetail",
    Work_Progress_Upload: "WorkProgressUpload",
    Building_Issues: "BuildingIssues",
    Milestone_Rejection_Comments: "MilestoneRejectionComments",
    Conclusion_Accepted: "ConclusionAccepted",
    Notification: "Notification",
    Property_Manager_List: "PropertyManagerList",
    Property_Manager_Details: "PropertyManagerDetails",
    Clients_List: "ClientsList",
    Clients_Details: "ClientsDetails",
    Add_Job_Code: "AddJobCode",
    Payment_Done: "PaymentDone",
    Payment_Processing: "PaymentProcessing",
    Edit_Milestone: "EditMilestone",
    Ask_For_Modification: "AskForModification",
    Reject_Work: "RejectWork",
    TutorialScreen: "TutorialScreen",

    uboPersonDetails: 'uboPersonDetails',
    EditBusinessUBO1: 'EditBusinessUBO1',
    EditBusinessUBO2: 'EditBusinessUBO2',

    SecondaryBusinessPersonDetails: 'SecondaryBusinessPersonDetails',
    IncorporateMyProfile: 'IncorporateMyProfile',
    CompanyInformation: 'CompanyInformation',

    LegalInformation: 'LegalInformation',
    LegalContactInformation: 'LegalContactInformation',




}
